# Generated by Django 3.0.3 on 2020-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='userid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='应聘者ID'),
        ),
    ]
