# Generated by Django 3.0.3 on 2020-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=250, verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=250, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳'), (3, '杭州'), (4, '广州')], verbose_name='工作地点')),
                ('job_responsibility', models.CharField(max_length=1024, verbose_name='职位职责')),
                ('job_requirement', models.CharField(max_length=1024, verbose_name='职位要求')),
                ('creator_id', models.CharField(max_length=250, verbose_name='创建人')),
                ('created_date', models.DateField(verbose_name='创建日期')),
                ('modified_date', models.DateField(verbose_name='修改日期')),
            ],
        ),
    ]
