# Generated by Django 3.0.3 on 2020-08-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类'), (4, '市场营销类')], max_length=250, verbose_name='职位类别'),
        ),
    ]
